<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'Detection\\Cache\\Cache' => $vendorDir . '/mobiledetect/mobiledetectlib/src/Cache/Cache.php',
    'Detection\\Cache\\CacheException' => $vendorDir . '/mobiledetect/mobiledetectlib/src/Cache/CacheException.php',
    'Detection\\Cache\\CacheInvalidArgumentException' => $vendorDir . '/mobiledetect/mobiledetectlib/src/Cache/CacheInvalidArgumentException.php',
    'Detection\\Exception\\MobileDetectException' => $vendorDir . '/mobiledetect/mobiledetectlib/src/Exception/MobileDetectException.php',
    'Detection\\Exception\\MobileDetectExceptionCode' => $vendorDir . '/mobiledetect/mobiledetectlib/src/Exception/MobileDetectExceptionCode.php',
    'Detection\\MobileDetect' => $vendorDir . '/mobiledetect/mobiledetectlib/src/MobileDetect.php',
    'Detection\\MobileDetectStandalone' => $vendorDir . '/mobiledetect/mobiledetectlib/src/MobileDetectStandalone.php',
    'Psr\\SimpleCache\\CacheException' => $vendorDir . '/psr/simple-cache/src/CacheException.php',
    'Psr\\SimpleCache\\CacheInterface' => $vendorDir . '/psr/simple-cache/src/CacheInterface.php',
    'Psr\\SimpleCache\\InvalidArgumentException' => $vendorDir . '/psr/simple-cache/src/InvalidArgumentException.php',
);
